### ISSUE TITLE
Expect receive vs expect have received

### ISSUE THREAD

**Issue by kraflab** [dawanda/rubocop-config#11]
This rule is pointless.  Besides the fact that `expect x to have received` makes no sense from the perspective of the english language, there are times where one makes more sense than the other for a particular example, so even enforcing in the other direction seems pointless to me.

```
engines:
  # ... CONFIG CONTENT ...
  rubocop:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Rubocop/RSpec/MessageSpies:
        enabled: false
# ... CONFIG CONTENT ...
```
