### ISSUE TITLE
# frozen_string_literal: true

### ISSUE THREAD

**Issue by kraflab** [dawanda/rubocop-config#8]
In ruby 2.3, you can add a comment at the top of a file to freeze all string literals, since this will be default behaviour in an upcoming ruby version.  Code climate complains on *every* file that doesn't do this.  I don't think there's any reason to have this rule enabled.

```
engines:
  # ... CONFIG CONTENT ...
  rubocop:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
# ... CONFIG CONTENT ...
```
